/** Usage text for every command, kept in one place. */

const WORKSPACE_NOTE = [
  "Workspace:",
  "  --workspace <dir> is THE isolation mechanism: each isolated directory",
  "  gets its own runs.db and artifacts. Resolution order when --workspace",
  "  is absent: $INSPECTOR_WORKSPACE, then the process working directory",
  "  (note: `pnpm run` re-cwd's to the package directory, so prefer an",
  "  explicit --workspace). A warning is printed when the resolved workspace",
  "  is the Inspector repository root.",
].join("\n");

const GLOBAL = [
  "Global flags:",
  "  --json                Machine-readable JSON output",
  "  --workspace <dir>     Workspace directory (see Workspace below; default:",
  "                        $INSPECTOR_WORKSPACE, else <cwd>/.inspector)",
  "  --debug               Print raw stack traces after errors",
  "  --version, -v         Print the Inspector version",
  "  --help, -h            Show help for a command",
].join("\n");

export function generalUsage(): string {
  return [
    "inspector - autonomous, durable environment inspection and defect discovery",
    "",
    "Usage: inspector <command> [flags]",
    "",
    "Commands:",
    "  doctor                   Probe platform capabilities and workspace health",
    "  hunt                     Unscripted autonomous exploration against a target",
    "  run                      Scripted demonstration scenario (fake|web adapters)",
    "  runs list|show|resume    Inspect and re-attach to recorded runs",
    "  findings list|show       Inspect discovered findings and evidence bundles",
    "  verify <findingId>       Replay one durable finding",
    "  regress                  Replay durable regression scenarios",
    "  explore                  Explore coverage without patching",
    "  repair <findingId>       Run isolated repair (explicit provider required)",
    "  campaign run|validate|list|show  Operate bounded scale campaigns",
    "  models summary           Inspect durable model-call accounting",
    "  help [command]           Show help",
    "",
    GLOBAL,
    "",
    WORKSPACE_NOTE,
    "",
    "Examples:",
    "  inspector doctor --json",
    "  inspector hunt --adapter web --max-actions 100 --max-minutes 5",
    "  inspector hunt --adapter web --url http://127.0.0.1:3000/ --seed 7",
    "  inspector hunt --adapter fake --max-actions 60 --json",
    "  inspector hunt --resume run_abc123 --json",
    "  inspector findings list --limit 20",
    "  inspector findings show find_abc123",
    "  inspector runs list",
    "  inspector runs resume run_abc123",
    "",
    "Machine exit codes: 0 success; 2 reproduced finding/regression;",
    "3 environment unavailable/flaky; 4 user/config or policy refusal;",
    "1 internal Inspector error. JSON failures use schema inspector-cli/error/1.",
  ].join("\n");
}

const COMMAND_HELP: Record<string, string> = {
  doctor: [
    "Usage: inspector doctor [--json] [--workspace <dir>]",
    "",
    "Probes the local platform and reports {ok, detail, remediation} per check.",
    "Core checks (node >= 22, workspace writable, store opens, fake adapter",
    "resolvable) must pass; optional capability probes (web/Playwright, pty,",
    "android adb, windows-uia, electron) are reported as WARN when missing.",
    "",
    "Exit code 0 only when all core checks pass.",
    "",
    WORKSPACE_NOTE,
  ].join("\n"),
  hunt: [
    "Usage: inspector hunt [--adapter web|fake|cli|windows|android|electron] [options]",
    "",
    "Unscripted autonomous exploration: discovers anomalies, reproduces them,",
    "and writes evidence bundles under <workspace>/bundles/<runId>/.",
    "",
    "Options:",
    "  --adapter web|fake|cli|windows|android|electron  Target adapter (default: web)",
    "  --url <u>              Web only: external localhost http(s) target",
    "                         (validated; forwarded via WEB_TARGET_URL)",
    "                         Electron targets the bundled seeded fixture only.",
    "  --seed <n>             Deterministic exploration seed (default: 7)",
    "  --max-actions <n>      Action budget (default: 200)",
    "  --max-minutes <m>      Wall-clock budget in minutes (default: 10)",
    "  --max-findings <n>     Stop after N confirmed findings (default: 4)",
    "  --resume <runId>       Continue that durable autonomous campaign in a",
    "                         fresh Inspector process; original target/config",
    "                         are loaded and incompatible overrides are refused",
    "",
    "Model assistance (optional; provider-neutral, web explorer):",
    "  --model-provider <m>   Trusted local provider module (ESM/CJS)",
    "  --planner              Enable the semantic exploration planner",
    "  --semantic-oracle      Evaluate weak semantic suspicion on anomalies",
    "  --summarize            Enable bounded session-digest summarization",
    "  --model-max-requests <n>  Standalone request ceiling (durable gate)",
    "  --model-max-tokens <n>    Standalone token ceiling",
    "  --model-timeout-ms <n>    Per-call deadline (default: 8000)",
    "  --model-max-calls <n>     Absolute planner calls per run (default: 24)",
    "",
    "Budget permission is obtained BEFORE any model call; denied calls never",
    "reach a provider. Without a provider everything stays deterministic.",
    "",
    "JSON schema: inspector-cli/hunt/1. Exit code 1 on adapter-error /",
    "initial-observe-failed stops or any error-level finding outcome; otherwise 0.",
    "",
    WORKSPACE_NOTE,
  ].join("\n"),
  explore: [
    "Usage: inspector explore [--adapter web|fake|cli|windows|android|electron] [options]",
    "",
    "Explicit coverage exploration workflow. It records durable exploration",
    "campaign/checkpoint state, reports actions, states, resets, novelty, and",
    "finding observations, and supports --resume after an interrupted process.",
    "Exploration is discovery-only: it never applies a repair patch.",
    "",
    "Options:",
    "  --adapter web|fake|cli|windows|android|electron  Target adapter (default: web)",
    "  --url <u>              Web only: external localhost http(s) target",
    "  --target <value>       Native target hint",
    "  --seed <n>             Deterministic exploration seed (default: 7)",
    "  --max-actions <n>      Action budget (default: 200)",
    "  --max-minutes <m>      Wall-clock budget in minutes (default: 10)",
    "  --max-findings <n>     Stop after N confirmed findings (default: 4)",
    "  --resume <runId>       Continue that durable exploration campaign",
    "",
    "JSON schema: inspector-cli/explore/1. Exit code semantics match hunt;",
    "patching remains disabled regardless of discovery results.",
    "",
    WORKSPACE_NOTE,
  ].join("\n"),
  run: [
    "Usage: inspector run --adapter fake|web [--json]",
    "",
    "Scripted demonstration scenario against the chosen adapter. Records a",
    "durable run in the workspace store.",
    "",
    WORKSPACE_NOTE,
  ].join("\n"),
  runs: [
    "Usage: inspector runs list [--limit n]",
    "       inspector runs show <id>",
    "       inspector runs resume <id>",
    "",
    "  list     Most recent runs (id, status, adapter, created). Empty stores",
    "           print 'no runs recorded'.",
    "  show     Steps and outcomes for one run.",
    "  resume   Diagnostic environment re-attachment only: mark in-flight",
    "           actions unknown and print a re-observed summary. It does not",
    "           continue autonomous exploration; use 'hunt --resume <id>'.",
    "           Fails honestly when the original adapter kind is not",
    "           recoverable from the stored record.",
    "",
    WORKSPACE_NOTE,
  ].join("\n"),
  findings: [
    "Usage: inspector findings list [--run <id>] [--limit n]",
    "       inspector findings show <id>",
    "",
    "  list     Findings (newest first), optionally filtered by run.",
    "  show     One finding with status history, reproduction stats, artifact",
    "           refs count, and the evidence bundle path when it exists on disk.",
    "",
    WORKSPACE_NOTE,
  ].join("\n"),
  verify: [
    "Usage: inspector verify <findingId> [options]",
    "",
    "Recreates the finding's durable target provenance and replays its minimized",
    "evidence. It reports reproduced, fixed, flaky, environment-failure, or",
    "invalid-provenance without treating automation misses as target defects.",
    "",
    "Options:",
    "  --attempts <n>           Replay attempts (default: 2)",
    "  --min-successes <n>      Reproductions required (default: 1)",
    "  --timeout-ms <n>         Bound each replay attempt",
    "  --revision <value>       Require an exact finding revision",
    "",
    WORKSPACE_NOTE,
  ].join("\n"),
  regress: [
    "Usage: inspector regress [options]",
    "",
    "Replays confirmed/resolved/regressed findings using their durable minimized",
    "scenarios. Completed scenario keys are reported as explicit skips so a",
    "controller restart cannot silently duplicate work.",
    "",
    "Options:",
    "  --run <id>               Restrict to one originating run",
    "  --finding <id>           Restrict to one finding",
    "  --adapter <family>       Restrict to one adapter identity",
    "  --revision <value>       Target an explicit revision label",
    "  --attempts <n>           Attempts per scenario (default: 1)",
    "  --min-successes <n>      Reproductions required (default: 1)",
    "  --limit <n>              Maximum findings to enumerate",
    "",
    WORKSPACE_NOTE,
  ].join("\n"),
  repair: [
    "Usage: inspector repair <findingId> --repo-root <dir> --revision <rev>",
    "                         --provider <module> [options]",
    "",
    "Runs the existing RepairEngine against one CONFIRMED finding. The exact",
    "revision is resolved before worktree creation and every patch is evaluated",
    "in a detached isolated worktree with regression-first, test-tampering,",
    "masking, and exact-replay gates.",
    "",
    "The provider is mandatory and explicit. It must export an object (or",
    "createRepairProvider(context)) implementing the existing PatchAgent,",
    "driverFor, OracleSuite, and non-empty maskingProbe contracts. No provider",
    "means repair refuses to start; no patch is applied to the primary checkout.",
    "",
    "Options:",
    "  --repo-root <dir>       Source repository to inspect (required)",
    "  --revision <rev>        Exact base revision or resolvable ref (required)",
    "  --provider <module>     Explicit provider module (required)",
    "  --patch-agent <module>  Alias for --provider",
    "  --max-attempts <n>      Patch-attempt budget (default: 2)",
    "  --error-text <text>     Optional diagnostic hint for the provider",
    "  --selectors <a,b>       Optional selector hints for source context",
    "",
    "Exit 0 only for RESOLVED; 2 for a rejected/unresolved repair outcome;",
    "3 for an environment/internal failure; 4 for policy/provenance refusal.",
    "JSON schema: inspector-cli/repair/1.",
    "",
    WORKSPACE_NOTE,
  ].join("\n"),
  campaign: [
    "Usage: inspector campaign run --manifest campaign.yaml [options]",
    "       inspector campaign validate --manifest campaign.yaml",
    "       inspector campaign run --items id=target,id=target [options]",
    "       inspector campaign list [--limit n]",
    "       inspector campaign show <id>",
    "       inspector campaign stop <id>",
    "       inspector campaign resume <id>",
    "",
    "Runs the existing bounded @inspector/scale controller with durable",
    "leases, resource accounting, isolated per-item workspaces, finding",
    "clustering, capability-aware worker routing, and restart-safe",
    "completion fencing.",
    "",
    "Manifests (YAML or JSON) describe complex campaigns; they are fully",
    "validated before any work starts. Example:",
    "",
    "  schema: inspector-campaign-manifest/1",
    "  id: nightly-fleet",
    "  workers: 3",
    "  items:",
    "    - id: web-hunt-1",
    "      workflow: hunt          # hunt|explore|verify|regress|repair",
    "      adapterFamily: web      # fake|web|cli|windows|android|electron",
    "      targetUri: http://127.0.0.1:8091/",
    "      seed: 7",
    "      budgets: { maxActions: 120, maxMinutes: 6 }",
    "      requiresCapabilities: [browser]",
    "    - id: fake-warmup",
    "      workflow: hunt",
    "      adapterFamily: fake",
    "      steps: 4",
    "",
    "Repair requires explicit per-item `repairAuthorized: true` AND a",
    "configured patch provider; discovery never implies repair.",
    "",
    "Run options:",
    "  --id <id>              Stable campaign id (generated when omitted)",
    "  --manifest <path>      Campaign manifest file (YAML or JSON)",
    "  --items <a=fake,b=fake> Legacy quick-path assignments (fake targets)",
    "  --workers <n>           Bounded worker count (default: manifest or 2)",
    "  --steps <n>             Per-item action bound for the quick path (default: 4)",
    "  --seed <n>              First deterministic quick-path seed (default: 7)",
    "  --mode hunt|regression|repair  Quick-path item mode (default: hunt)",
    "  --max-actions <n>       Global action budget",
    "  --max-worker-actions <n> Per-worker action budget",
    "  --max-tokens <n>        Global token budget",
    "  --max-cost-usd <n>      Global cost budget",
    "  --lease-backend json|sqlite  Durable lease backend (default: sqlite)",
    "  --lease-ttl-ms <n>      Lease expiry bound (default: 60000)",
    "  --max-minutes <n>       Wall-clock bound (default: 10)",
    "",
    "JSON schemas: inspector-cli/campaign/1, campaign-list/1,",
    "campaign-show/1, campaign-validate/1. Exit 2 when one or more items",
    "fail; exit 4 for invalid manifests/configuration; stop/resume are",
    "cooperative and durable across controller restarts.",
    "",
    WORKSPACE_NOTE,
  ].join("\n"),
  help: ["Usage: inspector help [command]", "", "Show help for a command."].join("\n"),
  models: [
    "Usage: inspector models summary [--limit n] [--json]",
    "",
    "Aggregate view of the durable model-call control plane: attempts,",
    "completions, failures by classification, denials, crash-window rows,",
    "known token/cost sums (NULL when no provider reported usage), and the",
    "most recent attempts with attribution. Raw prompts/responses are never",
    "persisted; only hashes and bounded metadata exist.",
    "",
    "Options:",
    "  --limit <n>            Recent rows to list (default: 20)",
    "",
    "JSON schema: inspector-cli/models/1.",
    "",
    WORKSPACE_NOTE,
  ].join("\n"),
};

export function commandHelp(command: string): string {
  return COMMAND_HELP[command] ?? generalUsage();
}
