/** Usage text for every command, kept in one place. */

const WORKSPACE_NOTE = [
  "Workspace:",
  "  --workspace <dir> is THE isolation mechanism: each isolated directory",
  "  gets its own runs.db and artifacts. Resolution order when --workspace",
  "  is absent: $INSPECTOR_WORKSPACE, then the process working directory",
  "  (note: `pnpm run` re-cwd's to the package directory, so prefer an",
  "  explicit --workspace). A warning is printed when the resolved workspace",
  "  is the Inspector repository root.",
].join("\n");

const GLOBAL = [
  "Global flags:",
  "  --json                Machine-readable JSON output",
  "  --workspace <dir>     Workspace directory (see Workspace below; default:",
  "                        $INSPECTOR_WORKSPACE, else <cwd>/.inspector)",
  "  --debug               Print raw stack traces after errors",
  "  --version, -v         Print the Inspector version",
  "  --help, -h            Show help for a command",
].join("\n");

export function generalUsage(): string {
  return [
    "inspector - autonomous, durable environment inspection and defect discovery",
    "",
    "Usage: inspector <command> [flags]",
    "",
    "Commands:",
    "  doctor                   Probe platform capabilities and workspace health",
    "  hunt                     Unscripted autonomous exploration against a target",
    "  run                      Scripted demonstration scenario (fake|web adapters)",
    "  runs list|show|resume    Inspect and re-attach to recorded runs",
    "  findings list|show       Inspect discovered findings and evidence bundles",
    "  help [command]           Show help",
    "",
    GLOBAL,
    "",
    WORKSPACE_NOTE,
    "",
    "Examples:",
    "  inspector doctor --json",
    "  inspector hunt --adapter web --max-actions 100 --max-minutes 5",
    "  inspector hunt --adapter web --url http://127.0.0.1:3000/ --seed 7",
    "  inspector hunt --adapter fake --max-actions 60 --json",
    "  inspector hunt --resume run_abc123 --json",
    "  inspector findings list --limit 20",
    "  inspector findings show find_abc123",
    "  inspector runs list",
    "  inspector runs resume run_abc123",
  ].join("\n");
}

const COMMAND_HELP: Record<string, string> = {
  doctor: [
    "Usage: inspector doctor [--json] [--workspace <dir>]",
    "",
    "Probes the local platform and reports {ok, detail, remediation} per check.",
    "Core checks (node >= 22, workspace writable, store opens, fake adapter",
    "resolvable) must pass; optional capability probes (web/Playwright, pty,",
    "android adb, windows-uia, electron) are reported as WARN when missing.",
    "",
    "Exit code 0 only when all core checks pass.",
    "",
    WORKSPACE_NOTE,
  ].join("\n"),
  hunt: [
    "Usage: inspector hunt [--adapter web|fake|cli|windows|android] [options]",
    "",
    "Unscripted autonomous exploration: discovers anomalies, reproduces them,",
    "and writes evidence bundles under <workspace>/bundles/<runId>/.",
    "",
    "Options:",
    "  --adapter web|fake|cli|windows|android  Target adapter (default: web)",
    "  --url <u>              Web only: external localhost http(s) target",
    "                         (validated; forwarded via WEB_TARGET_URL)",
    "  --seed <n>             Deterministic exploration seed (default: 7)",
    "  --max-actions <n>      Action budget (default: 200)",
    "  --max-minutes <m>      Wall-clock budget in minutes (default: 10)",
    "  --max-findings <n>     Stop after N confirmed findings (default: 4)",
    "  --resume <runId>       Continue that durable autonomous campaign in a",
    "                         fresh Inspector process; original target/config",
    "                         are loaded and incompatible overrides are refused",
    "",
    "Exit code 1 on adapter-error / initial-observe-failed stops or any",
    "error-level finding outcome; otherwise 0.",
    "",
    WORKSPACE_NOTE,
  ].join("\n"),
  run: [
    "Usage: inspector run --adapter fake|web [--json]",
    "",
    "Scripted demonstration scenario against the chosen adapter. Records a",
    "durable run in the workspace store.",
    "",
    WORKSPACE_NOTE,
  ].join("\n"),
  runs: [
    "Usage: inspector runs list [--limit n]",
    "       inspector runs show <id>",
    "       inspector runs resume <id>",
    "",
    "  list     Most recent runs (id, status, adapter, created). Empty stores",
    "           print 'no runs recorded'.",
    "  show     Steps and outcomes for one run.",
    "  resume   Diagnostic environment re-attachment only: mark in-flight",
    "           actions unknown and print a re-observed summary. It does not",
    "           continue autonomous exploration; use 'hunt --resume <id>'.",
    "           Fails honestly when the original adapter kind is not",
    "           recoverable from the stored record.",
    "",
    WORKSPACE_NOTE,
  ].join("\n"),
  findings: [
    "Usage: inspector findings list [--run <id>] [--limit n]",
    "       inspector findings show <id>",
    "",
    "  list     Findings (newest first), optionally filtered by run.",
    "  show     One finding with status history, reproduction stats, artifact",
    "           refs count, and the evidence bundle path when it exists on disk.",
    "",
    WORKSPACE_NOTE,
  ].join("\n"),
  help: ["Usage: inspector help [command]", "", "Show help for a command."].join("\n"),
};

export function commandHelp(command: string): string {
  return COMMAND_HELP[command] ?? generalUsage();
}
